### ISSUE TITLE
Switch from ClickOnce to Squirrel for installer

### ISSUE THREAD

**Issue by dsplaisted** [dsplaisted/NuGetPackageExplorer#2]
[Squirrel](https://github.com/Squirrel/Squirrel.Windows)

**Comment by 304NotModified** [comment]
How is this better than clickonce? 

I have no problems with clickonce expect I can get it working while hosting on github (page)

**Comment by augustoproiete** [comment]
Moved to:
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/15
