### ISSUE TITLE
Merge in

### ISSUE THREAD

**Issue by 304NotModified** [dsplaisted/NuGetPackageExplorer#4]
Proposal to merge form other forks:
- [ ] @rikoe: Support for pushing to authenticated NuGet feed
- [ ] @rikoe: Include default credentials in web requests
- [ ] @rikoe: Fallback to Packages() service for all versions
- [ ] @304notmodified: Added support for missing Framework version (Xamarin, Net452, net46, uap10)
- [ ] @304notmodified: Allow Replacement tokens (like $version$)

**Comment by 304NotModified** [comment]
Please add if things are missing

**Comment by 304NotModified** [comment]
@dsplaisted What do you think?

**Comment by dsplaisted** [comment]
Looks like a good list to me!  I'd love to see PRs for these.

**Comment by augustoproiete** [comment]
Moved to:
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/16
