### ISSUE TITLE
Create github organisation 

### ISSUE THREAD

**Issue by 304NotModified** [dsplaisted/NuGetPackageExplorer#6]
Because it now looks like a fork.

**Comment by dsplaisted** [comment]
Looks like you've done this and added the code there.

There's several issues tracked in dsplaisted/NuGetPackageExplorer.  We could just move the entire repo under the new organization, but that would mean deleting the existing repo there.  Or we could just copy the issues manually.

Thoughts?

**Comment by 304NotModified** [comment]
To be sure,  you mean https://github.com/dsplaisted/NuGetPackageExplorer/issues ? 

Let's copy them manually.  No problem in doing that.

**Comment by augustoproiete** [comment]
:+1: to move the repo to the org.

I've manually copied all the issues to [there](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues) (with the exception of this one, of course)

**Comment by 304NotModified** [comment]
Thanks for your help :)
